add and fix
WildCodeSchool/rogue-one pull request #18
Opened 2024-01-04 11:01 UTC by joelmayemba

- Ajout des pages Home, Mocktails, Contact et A propos
- Ajout de la navbar, du footer
- Ajout du logo/favicon
- Ajout des images des mocktails, des membres de l'équipe

2024-01-04 13:27 UTC, Benja-san requested changes

2024-01-04 13:27 UTC, Benja-san commented on assets/css/about.css
> +#notre-histoire {
use english classnames and ids (and variables and functions)

2024-01-04 13:27 UTC, Benja-san commented on assets/js/custom.js
> +    var scroll = $(window).scrollTop();
never use var but const or let keyword

2024-01-04 13:27 UTC, Benja-san commented on assets/js/custom.js
> +  $(window).on("load", function () {
avoid jquery

2024-01-04 13:27 UTC, Benja-san commented on assets/js/custom.js
> +(function ($) {
please refactor this file to remove any jquery use (if possible before tomorrow presentation, if not you will refactor it during project 2)

2024-01-04 13:27 UTC, Benja-san commented on include/footer.php
> +        <div class="row">
change div tag for nav tag

2024-01-04 13:27 UTC, Benja-san commented on include/navbar.php
> +        <div class="row">
change div for nav tag

2024-01-04 13:27 UTC, Benja-san commented on include/profil_cards.php
> +            echo '<div class="col-md-4">
insert php inside html rather than html in php (better practice)

2024-01-04 13:27 UTC, Benja-san commented on include/profil_cards.php
> +                <h6>' . $member["role"] . '</h6>
where is the h5 ?

2024-01-04 13:27 UTC, Benja-san commented on pages/about.php
> +          <h3>À propos de nous</h3>
where is the h1 ?

2024-01-04 13:27 UTC, Benja-san commented on include/navbar.php
> +                        <h1>Mocktail</h1>
since h1 should be different on each page, keep only a tag for index link but use h1 inside pages

2024-01-04 13:27 UTC, Benja-san commented on pages/contact.php
> +          <h3>Nous contacter</h3>
where is h1 and h2 ?

2024-01-04 13:27 UTC, Benja-san commented on pages/home.php
> +          <h2>Éveillez vos sens avec nos mocktails tendance :<br> </h2>
h1

2024-01-04 13:27 UTC, Benja-san commented on pages/mentions_legales.php
> +<P>Mentions Légales
add at least one title h1

2024-01-04 13:27 UTC, Benja-san commented on pages/mocktails-details.php
> +            <h4><?php $cocktails["id"]?></h4>
respect h hierarchy

2024-01-04 13:27 UTC, Benja-san commented on pages/mocktails.php
> +          <div class="col-lg-4 col-md-6 align-self-center mb-30 mocktails-items col-md-6 ' . $normalizedCategory . '">
insert php inside html rather than html inside php

2024-01-04 13:27 UTC, Benja-san commented on pages/mocktails.php
> +        <div class="product-details" style="display: none;">
avoid inline style

2024-01-04 13:27 UTC, Benja-san commented on pages/mocktails.php
> +  <script>
avoid js inside php / html files

2024-01-05 10:47 UTC, Benja-san approved these changes

2024-01-05 10:47 UTC, Benja-san commented on assets/css/about.css
> +#notre-history {
it was the "notre" in french which was a problem haha

2024-01-05 10:52 UTC, KevinGIRAULT approved these changes

2024-01-05 10:52 UTC, merged

2024-01-05 10:52 UTC, chouaibj approved these changes